services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: assetflow_backend
    restart: always
    ports:
      - "5328:5328"
    volumes:
      # üëá AQUI EST√Å A CORRE√á√ÉO: Mapeamos para dentro da pasta /server/
      - ./assetflow.db:/app/server/assetflow.db
      - ./backups:/app/backups
    environment:
      - FLASK_ENV=production

  frontend:
    build: .
    container_name: assetflow_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5328
    depends_on:
      - backend